### ISSUE TITLE
Lots of images for you! 🖼

### ISSUE THREAD

**Issue by KTibow** [bessarabov/home-assistant-cards#2]
mini-media-player:
![media-player](https://user-images.githubusercontent.com/10727862/92958402-0566ad00-f41f-11ea-82d2-c4da2c967f1b.png)
banner-card:
![banner-card](https://user-images.githubusercontent.com/10727862/92959204-385d7080-f420-11ea-8efb-e89e6b99488d.png)
vacuum-card:
![vacuum-card](https://user-images.githubusercontent.com/10727862/92959615-fda80800-f420-11ea-97fc-8b3eef91e41d.png)
Other notes:
You should probably remove mod-card (which is a plugin, not a card), layout-card and stack-card (which just create a layout for other cards), and auto-entities (which just passes parameters to a card).
Also mind double-checking all images in the database for 492 pixels wideness?

**Comment by bessarabov** [comment]
Super! Thank you!

I've added images mini-media-player & vacuum-card to this repo — https://github.com/bessarabov/home-assistant-cards/commit/117ad9b75e2848ce792142f0bea7ee0750dad44a (They are already live at https://home-assistant-cards.bessarabov.com/ )

(I've checked the width of that cards and it was expected 492 px)

But I need some time to think about your images for the vertical-stack-in-card and banner-card, and about your proposal to remove some cards.

**Comment by bessarabov** [comment]
@KTibow KTibow, Thank you again for your work.

I'm not going to add you image for banner card, because it does not represent the common use case of it.

I was thinking about your proposal to remove some cards and I think that now I understand the logic, what I want to see here and what I do not. This repo contains everything that is a card — it means that you can add it to Home Assistant UI, something like:

```
title: home

views:

  - title: control
    path: default_view
    cards:
      - type: NNNNNN
```
 
Even if there is no visible part of the card, this card can be here. `layout-card`, `auto-entities` cards can be used in NNNNNN of the above code, so it is ok that they are here (by the way, that things are super useful and popular, I'm sure that they need to be here)

I'm not sure what stack card you are reffering to. There are 2 cards with the word `stack` in the name:

 * https://github.com/ofekashery/vertical-stack-in-card
 * https://github.com/custom-cards/stack-in-card

I'm happy to see both that cards in this repo.

Mod card is a bit special, but it has the ability to be used as a card (https://github.com/thomasloven/lovelace-card-mod#styling-cards-without-an-ha-card-element), so I like to see info about this card in this repo.
